### ISSUE TITLE
Update collapsible div behavior after searching for address/adjusting filters

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/cob-maps#30]
When viewing the map on a small screen, the menu div should collapse to clear the screen after the user searches for an address or makes filter selections.  

Example of properly working: http://cob-maps-dev.herokuapp.com/city_council.html

Other maps that need this implemented on:
- [food trucks](https://www.boston.gov/departments/small-business-development/city-boston-food-trucks-schedule)
- [public bathrooms](http://cob-maps-dev.herokuapp.com/public_bathrooms.html)
- [farmers markets](https://www.boston.gov/departments/food-access/farmers-markets-boston)
- [snow emergency parking](https://www.boston.gov/departments/311/snow-emergency-parking)

**Comment by fionawhim** [comment]
@paylakatel Do you think we could close this since it'll be fixed in the new maps components?

**Comment by paylakatel** [comment]
Yeah, for sure.
